"""Test script for RAG and LLM features"""
import requests
import json

BASE_URL = "http://127.0.0.1:8000/api/v1"
HEADERS = {
    "Content-Type": "application/json",
    "X-Principal-Subject": "test-user",
    "X-Tenant-ID": "default"
}

def test_job_description_generation():
    """Test LLM job description generation"""
    print("=" * 60)
    print("Test 1: Generate Job Description with LLM")
    print("=" * 60)
    
    response = requests.post(
        f"{BASE_URL}/ai/jobs/generate-description",
        headers=HEADERS,
        json={
            "title": "Senior Python Developer",
            "department": "Engineering",
            "level": "senior",
            "required_skills": ["Python", "FastAPI", "MongoDB", "Docker"],
            "responsibilities": [
                "Design and develop RESTful APIs",
                "Write clean, maintainable code",
                "Mentor junior developers"
            ],
            "use_llm": True
        }
    )
    
    if response.status_code == 200:
        result = response.json()
        print(f"Status: {response.status_code}")
        print(f"Generated by: {result.get('generated_by')}")
        print(f"Description length: {len(result.get('description', ''))} characters")
        print("\nGenerated Description (first 500 chars):")
        print(result.get('description', '')[:500])
        print("...")
        return True
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
        return False


def test_semantic_search():
    """Test semantic job search"""
    print("\n" + "=" * 60)
    print("Test 2: Semantic Job Search")
    print("=" * 60)
    
    response = requests.post(
        f"{BASE_URL}/ai/jobs/search-semantic",
        headers=HEADERS,
        json={
            "query": "Python backend developer with API and database experience",
            "limit": 5,
            "filters": {"status": "published"}
        }
    )
    
    if response.status_code == 200:
        results = response.json()
        print(f"Found {len(results)} matching jobs:")
        for i, job in enumerate(results, 1):
            print(f"\n{i}. {job.get('title')}")
            print(f"   Score: {job.get('score', 0):.2%}")
            print(f"   Department: {job.get('department', 'N/A')}")
            print(f"   Level: {job.get('level', 'N/A')}")
        return len(results) > 0
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
        return False


def test_question_answering():
    """Test job question answering"""
    print("\n" + "=" * 60)
    print("Test 3: Question Answering (RAG)")
    print("=" * 60)
    
    # Get a job ID first
    jobs_response = requests.get(
        "http://127.0.0.1:8000/jobs/",
        params={"limit": 1}
    )
    
    if jobs_response.status_code == 200 and jobs_response.json():
        job_id = jobs_response.json()[0].get("id")
        
        response = requests.post(
            f"{BASE_URL}/ai/jobs/{job_id}/ask",
            headers=HEADERS,
            json={
                "question": "What skills are required for this position?",
                "job_id": job_id
            }
        )
        
        if response.status_code == 200:
            result = response.json()
            print(f"Question: What skills are required for this position?")
            print(f"Job ID: {job_id}")
            print(f"\nAnswer:")
            print(result.get('answer', 'No answer'))
            return True
        else:
            print(f"Error: {response.status_code}")
            print(response.text)
            return False
    else:
        print("No jobs found to test with")
        return False


def test_candidate_matching():
    """Test candidate-job matching"""
    print("\n" + "=" * 60)
    print("Test 4: Candidate-Job Matching")
    print("=" * 60)
    
    response = requests.post(
        f"{BASE_URL}/ai/jobs/match-candidate",
        headers=HEADERS,
        json={
            "skills": ["Python", "FastAPI", "MongoDB"],
            "experience_summary": "3 years of Python backend development",
            "years_of_experience": 3,
            "desired_role": "Software Engineer"
        }
    )
    
    if response.status_code == 200:
        results = response.json()
        print(f"Found {len(results)} matching jobs:")
        for i, match in enumerate(results[:3], 1):
            print(f"\n{i}. {match.get('job_title')}")
            print(f"   Match Score: {match.get('match_score', 0):.2%}")
            print(f"   Matched Skills: {', '.join(match.get('matched_skills', []))}")
            if match.get('missing_skills'):
                print(f"   Missing Skills: {', '.join(match.get('missing_skills', []))}")
        return len(results) > 0
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
        return False


if __name__ == "__main__":
    print("\n")
    print("=" * 60)
    print("RAG & LLM Feature Testing")
    print("=" * 60)
    print("\nMake sure the server is running at http://127.0.0.1:8000")
    print("\n")
    
    results = []
    
    # Test 1: Job Description Generation
    results.append(("Job Description Generation", test_job_description_generation()))
    
    # Test 2: Semantic Search (may fail if jobs not indexed)
    results.append(("Semantic Search", test_semantic_search()))
    
    # Test 3: Question Answering
    results.append(("Question Answering", test_question_answering()))
    
    # Test 4: Candidate Matching
    results.append(("Candidate Matching", test_candidate_matching()))
    
    # Summary
    print("\n" + "=" * 60)
    print("Test Summary")
    print("=" * 60)
    for name, success in results:
        status = "PASSED" if success else "FAILED/SKIPPED"
        print(f"{name}: {status}")
    
    print("\n" + "=" * 60)

